version: '3'

services:
  docmost:
    # image: docmost/docmost:latest
    build:
      context: .
      dockerfile: Dockerfile 
    depends_on:
      - redis
    environment:
      APP_URL: ${APP_URL}
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      NODE_ENV: "production"
    ports:
      - "${PORT}:5173"
    restart: unless-stopped
    volumes:
      - docmost:/app/data/storage

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  docmost:
  redis_data: